config/routes.rb
Rails.application.routes.draw do
  get 'swatch-test/index'

  get 'sketch/show'

  get 'storyboard/show'

  root 'storyboard#show'
end

app/models/concerns/validate_email.rb
module ValidateEmail
  extend ActiveSupport::Concern

  class EmailValidator < ActiveModel::EachValidator

    def validate_each(record, attribute, value) 
      unless value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
        record.errors[attribute] << (options[:message] || "is not a valid email")
      end
    end
  end
end

app/models/participant.rb
class Participant < ActiveRecord::Base
  include ValidateEmail
  belongs_to :storyboard
  validates :email, presence: true, email: true
  validates :storyboard_id, presence: true
  after_save :find_or_create_designer

private
  def find_or_create_designer
    @designer = Designer.find_or_create_by(email: self.email)
  end
end

app/models/sketch.rb
class Sketch < ActiveRecord::Base
  belongs_to :designer
  belongs_to :storyboard
  validates :designer_id, presence: true
  validates :storyboard_id, presence: true
  validates :url, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::API
  before_filter :authenticate!

private
  def authenticate!
    @authenticated_user = Designer.find_by(auth_token: request.headers["Auth-Token"])
    render :json => { error: "Invalid token." }, 
        success: :false, status: :unauthorized unless @authenticated_user
  end

  def current_designer
    @authenticated_user
  end
end

app/controllers/concerns/push_message.rb
module PushMessage
  extend ActiveSupport::Concern
  include PushServer

  def push_message(channel,viewer)
    HTTParty.get("http://#{push_server_uri}/#{channel}?viewer_id=#{viewer.id}&avatar_url=#{viewer.avatar_url}")
  end
end

app/controllers/concerns/push_server.rb
module PushServer
  extend ActiveSupport::Concern

  def push_server_uri
    if Rails.env.development? 
      return ENV['PUSH_DEV']
    end
    if Rails.env.production? ENV['PUSH_PROD']
      return ENV['PUSH_PROD']
    end
  end
end

app/controllers/concerns/storyboard_participants.rb
module StoryboardParticipants
  extend ActiveSupport::Concern

  # POST /storyboards/1/invite
  def invite
    if @storyboard.participants.count <= 4 # + storyboard creator = 5 participants
      @participant = @storyboard.participants.new(params.require(:storyboard).permit([:email]))
      @storyboard = current_designer.storyboards.new(params.require(:storyboard).permit([:name, :designer_id]))
      if @participant.save
        head status: :created
      else
        render json: @participant.errors, status: :unprocessable_entity
      end
    else
      render :json => {
        error: "Cannot exceed 5 participants."
        }, success: :false, status: :unprocessable_entity
    end
  end

  # GET /storyboards/1/participants
  def get_participants
    render json: @storyboard.participants.select(:id).uniq, except: :email
  end
end

app/controllers/concerns/storyboard_viewers.rb
module StoryboardViewers
  extend ActiveSupport::Concern
  include PushMessage

  # PATCH/PUT /storyboards/1/viewer
  def set_viewer
    @designer = Designer.find_by(auth_token: request.headers["Auth-Token"])
    @designer.viewing_storyboard_id = @storyboard.id
    @designer.save
    push_message('viewers', @designer)
  end

  # GET /storyboards/1/viewers
  def get_viewers
    @designers = Designer.where(viewing_storyboard_id: @storyboard.id)
    @viewing = []
    @designers.each {|v| @viewing << v }
    render :json => { viewers: @viewing }, except: [:auth_token, :storyboard_id]
  end
end

app/controllers/concerns/storyboards.rb
module Storyboards
  extend ActiveSupport::Concern

  # Returns only those storyboards that the designer created
  # or was invited to participate in
  def storyboards
    @storyboards = []
    # Find the storyboards they created
    current_designer.storyboards.each {|s|
      @storyboards << s
    }
    # Find the storyboards where they are a participant
    Participant.where(id: current_designer.id).each {|p|
      Storyboard.where(id: p.storyboard_id).each {|s|
        @storyboards << s
      }
    }
    return @storyboards.uniq
  end
end

app/controllers/designers_controller.rb
class DesignersController < ApplicationController
  include Storyboards

  wrap_parameters :designer, include: [:email, :avatar_url]
  skip_before_filter :authenticate!, only: [:create]
  before_filter :find, only: [:show, :update]

  def find
    @designer = Designer.find(params[:id])
  end

  # GET /designers
  def index
    @designers = []
    storyboards.each {|s|
      s.participants.each {|p|
        @designers << Designer.where(id: p.email)
      }
    }
    render json: @designers, except: [:auth_token]
  end

  # GET /designers/1
  def show
    render json: @designer, except: [:auth_token, :storyboard_id, :viewing_storyboard_id]
  end

  # POST /designers
  def create
    @designer = Designer.new(params.require(:designer).permit([:email, :avatar_url]))
    if @designer.save
      head status: :created, location: @designer, auth_token: @designer.auth_token
    else
      render json: @designer.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /designers/1
  def update
    if current_designer.id == @designer.id # prevent users from modifying each others settings (e.g., email and/or avatar)
      if @designer.update(params.require(:designer).permit([:auth_token, :avatar_url]))
        head :no_content
      else
        render json: @designer.errors, status: :unprocessable_entity
      end
    end
  end

  # DELETE /designers/1
  def destroy
    # @designer.destroy
    head :no_content
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  include PushServer
  skip_before_filter :authenticate!

  def about
    render :json => {
      name: 'Episketch',
      description: 'Share ideas with storyboards and sketches.',
      info: 'http://episketch.com/',
      push: "#{push_server_uri}"
    }
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  skip_before_filter :authenticate!, :only => [:create, :new]

  # GET /login
  def new
    head status: :no_content
  end

  # POST /login
  def create
    @designer = Designer.find_or_create_by(email: params[:email])
    if @designer
      head location: @designer, auth_token: @designer.auth_token
    else
      render json: @designer.errors, status: :unprocessable_entity,
        success: :false, status: :unauthorized
    end
  end

  # DELETE /logout
  def destroy
    head status: :accepted
  end
end

app/controllers/sketch_controller.rb
class SketchController < ApplicationController
  def show
  end
end

app/controllers/sketches_controller.rb
class SketchesController < ApplicationController
  wrap_parameters :sketch, include: [:url, :storyboard_id]
  before_filter :find, only: [:show, :update]

  def find
    @sketch = Sketch.find(params[:id])
  end

  # GET /sketches
  def index
    @sketches = current_designer.sketches
    render json: @sketches
  end

  # GET /sketches/1
  def show
    render json: @sketch
  end

  # POST /sketches
  def create
    @sketch = current_designer.sketches.new(params.require(:sketch).permit([:url, :designer_id, :storyboard_id]))
    if @sketch.save
      render json: @sketch, status: :created, location: @sketch
    else
      render json: @sketch.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /sketches/1
  def update
    if @sketch.update(params[:sketch])
      head :no_content
    else
      render json: @sketch.errors, status: :unprocessable_entity
    end
  end

  # DELETE /sketches/1
  def destroy
    # @sketch.destroy
    head :no_content
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/controllers/storyboard_controller.rb
class StoryboardController < ApplicationController
  def show
  end
end

app/controllers/swatch_test_controller.rb
class SwatchTestController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sketch_helper.rb
module SketchHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/storyboard_helper.rb
module StoryboardHelper
end

app/helpers/swatch_test_helper.rb
module SwatchTestHelper
end

app/views/sketch/show.html.haml
.row.pan.man
  .col-md-24.pan.man
    = link_to storyboard_show_path do
      .fa.fa-icon.fa-close.pull-right.h1.pan.man
.row
  .col-md-16
    %h2.statement.txt-c
      Versions
  .col-md-24
    .row
      .col-md-16
        = image_tag '/sample-sketches/sketch_5.png', class: 'img-responsive the-sketch'
      .col-md-8
        .created.mtxl
          .em-alt.type-sm
            Created 2 days ago by
          .created-by.pvxl
            = image_tag 'http://www.gravatar.com/avatar/8ebef7435ae7ad74f14b1c3d91f4ef17?size=256&default=404', class: 'img-circle avatar', width: 60, height: 60, style: 'border: none;'
            %span.h2.txt-m.mll Mike
          .description
            .em-alt.type-sm
              Description
            %p
              The BART train doors open. On the station wall there are two signs: go to the left for Montgomery; go to the right for Sansome.

app/views/static_pages/index.html.haml
%h1 StaticPages#index
%p Find me in app/views/static_pages/index.html.haml

app/views/storyboard/show.html.haml
.row
  .col-md-24
    %h2.statement.pal
      Make it easier for people to orient themselves when they emerge from a BART station
.row.clearfix
  #sketches
    .sketch.col-xs-12.col-sm-12.col-md-8.col-lg-8
      .sketch-img{ 'data-sketch-id' => '1'}
        = image_tag 'image-cover.png', class: 'img-responsive handle'
      %p.description.pvm
        1
    .sketch.col-xs-12.col-sm-12.col-md-8.col-lg-8
      .sketch-img{ 'data-sketch-id' => '2'}
        = image_tag 'image-cover.png', class: 'img-responsive handle'
      %p.description.pvm
        2
    .sketch.col-xs-12.col-sm-12.col-md-8.col-lg-8
      .sketch-img{ 'data-sketch-id' => '3'}
        = image_tag 'image-cover.png', class: 'img-responsive handle'
      %p.description.pvm
        3
    .sketch.col-xs-12.col-sm-12.col-md-8.col-lg-8
      .sketch-img{ 'data-sketch-id' => '4'}
        = image_tag 'image-cover.png', class: 'img-responsive handle'
      %p.description.pvm
        4
    .sketch.col-xs-12.col-sm-12.col-md-8.col-lg-8
      = link_to sketch_show_path do
        .sketch-img{ 'data-sketch-id' => '5'}
          = image_tag 'image-cover.png', class: 'img-responsive handle'
      %p.description.pvm
        5
    .sketch.col-xs-12.col-sm-12.col-md-8.col-lg-8
      .sketch-img{ 'data-sketch-id' => '6'}
        = image_tag 'image-cover.png', class: 'img-responsive handle'
      %p.description.pvm
        6

  .add-sketch.sketch.col-xs-12.col-sm-12.col-md-8.col-lg-8
    %label.pan.man{ for: 'addsketch'}
      .sketch-img
        .icon
          .fa.fa-icon.fa-camera
          .fa.fa-icon.fa-plus
        = image_tag 'image-cover.png', class: 'img-responsive handle', draggable: false
      %input#addsketch{ type: 'file', style: 'display: none;'}

app/views/swatch_test/index.html.haml
- dir = 'public/sample-sketches/'
- file_count = Dir[File.join(dir, '**', '*')].count { |file| File.file?(file) }
- random_image = rand(1..file_count)
.row
  .col-md-24#swatches
.row
  .col-md-24
    %h1.mtl.mbs
      = "Sample Image #{params[:id] ? params[:id] : random_image} of #{file_count}"
    %p.description
      This is a description of the image.
    .sketch-img{ 'data-sketch-id' => "#{params[:id] ? params[:id] : random_image}", style: 'background-size: cover;'}
      = image_tag 'image-cover.png', class: 'img-responsive'
    %p.caption.type-sm
      This is a caption of the image.